apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "svc-js.fullname" . }}
  namespace: svc-js
  labels:
    {{- include "svc-js.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "svc-js.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "svc-js.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
          - configMapRef:
              name: {{ include "svc-js.fullname" . }}
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 0.5
              memory: 512Mi

