apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc-js.fullname" . }}
  namespace: svc-js
  labels:
    {{- include "svc-js.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.name }}
    targetPort: {{ .Values.service.targetPort }}
    port: {{ .Values.service.port }}
  - name: {{ .Values.service.name2 }}
    targetPort: {{ .Values.service.targetPort2 }}
    port: {{ .Values.service.port2 }}
  selector:
    {{- include "svc-js.selectorLabels" . | nindent 4 }}
